# -*- coding: utf-8 -*-
"""app .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TKUpn1EwuW-JFKOd-PVglmCkvOMI4xz
"""

#best version

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # ==========================================
# # 1. KNOWLEDGE BASE: VARIABLES & "WHY" EXPLANATIONS
# # ==========================================
# # This dictionary maps the variable to the UI label and explains WHY the system asks it.
# QUESTIONS = {
#     "Engine & Mechanical": {
#         'eng_light': ("Engine Light ON", "To check for general engine faults, fuel injector issues, or sensor failures."),
#         'rpm_drop': ("RPM Drop", "To diagnose fuel injector failures or timing chain jumps."),
#         'trim': ("Fuel Trim > 15%", "High fuel trim indicates a potential vacuum leak or air-fuel mixture issue."),
#         'maf': ("MAF Reading Low", "To identify a dirty or failing Mass Air Flow sensor."),
#         'stall': ("Engine Stalling", "Critical symptom for throttle body, fuel pump, or fuel filter issues."),
#         'idle': ("Idle < 500 RPM", "Low idle points towards throttle body obstructions."),
#         'fuel_p': ("Fuel Pressure Low", "To confirm fuel pump failure or fuel delivery issues."),
#         'misfire': ("Misfire Detected", "Used to diagnose ignition breakdowns or clogged injectors."),
#         'gap': ("Spark Plug Gap Wide", "Helps confirm ignition breakdown issues."),
#         'pulse': ("Injector Pulse Weak", "Points directly to a clogged or failing fuel injector."),
#         'temp': ("Temp > 110C", "Critical for finding coolant leaks, dead fans, or thermostat failures."),
#         'coolant': ("Coolant Level Low", "Used to diagnose coolant leaks or heater core issues."),
#         'oil_p': ("Oil Pressure Low", "Identifies oil bleeding or oil pump failure."),
#         'oil_lvl': ("Oil Level Normal", "Helps differentiate between a severe leak and a mechanical pump failure."),
#         'knock': ("Knocking Sound", "Used to detect lubrication starvation or timing chain issues.")
#     },
#     "Transmission": {
#         'slip': ("Gear Slip", "Primary indicator of worn clutches or burnt transmission fluid."),
#         'trans_low': ("Trans Fluid Low", "Diagnoses hydraulic pressure loss or torque converter failure."),
#         'burnt': ("Fluid Burnt Smell", "Confirms burnt friction plates in the transmission."),
#         'harsh': ("Harsh Shift", "Points to hydraulic pressure loss or solenoid sabotage."),
#         'solenoid': ("No Solenoid Response", "Identifies electronic transmission failures."),
#         'trans_temp': ("Trans Temp High", "Used to diagnose overheated fluid from heavy loads."),
#         'load': ("Heavy Load/Towing", "Contextual question to explain high transmission temperatures."),
#         'no_drive': ("No Drive Engagement", "Checks for total torque converter failure."),
#         'vibr_accel': ("Vibration on Accel", "Used to diagnose driveline imbalance or broken mounts.")
#     },
#     "Brakes & Wheels": {
#         'click': ("Clicking on Turn", "Classic symptom used to diagnose a torn CV boot or ruined CV joint."),
#         'boot': ("CV Boot Torn", "Visual confirmation needed for CV joint failure."),
#         'brk_light': ("Brake Light ON", "Checks for fluid leaks, master cylinder failure, or shared sensor faults."),
#         'brk_low': ("Brake Fluid Low", "Confirms a brake fluid leak."),
#         'sink': ("Pedal Sinking", "Primary symptom of master cylinder internal failure."),
#         'squeal': ("Brake Squeal", "Used to diagnose worn out brake pads or glazed rotors."),
#         'pads': ("Pads Low", "Visual confirmation for pad wear out."),
#         'hard_p': ("Hard Brake Pedal", "Diagnoses glazed rotors, ABS pump failure, or steering rack issues."),
#         'spongy': ("Spongy Pedal", "Indicates air trapped in the brake lines."),
#         'bubbles': ("Air Bubbles in Fluid", "Confirms air in brake lines."),
#         'pulsation': ("Pedal Pulsation", "Used alongside shaking to diagnose warped rotors."),
#         'shake': ("Shake at High Speed", "Diagnoses warped rotors, tie rod play, or wheel bearing issues."),
#         'pull': ("Vehicle Pulls Aside", "Points to a seized brake caliper."),
#         'burning': ("Burning Smell", "Confirms a seized caliper dragging on the rotor."),
#         'abs_light': ("ABS Light ON", "Diagnoses ABS sensor or hydraulic pump failure."),
#         'wheel_err': ("Wheel Speed Err", "Checks for ABS sensor failures or system paralysis."),
#         'abs_pump': ("ABS Pump Noisy", "Confirms hydraulic ABS pump failure.")
#     },
#     "Electrical": {
#         'bat_light': ("Battery Light ON", "Checks for alternator undercharging or diode failures."),
#         'volt': ("Voltage < 13V", "Confirms the alternator is failing to charge the system."),
#         'ac_leak': ("AC Leakage detected", "Diagnoses a failed alternator diode bridge."),
#         'no_crank': ("No Cranking", "Used to check for a dead starter solenoid."),
#         'click_start': ("Clicking when starting", "Confirms starter solenoid issues."),
#         'slow_crank': ("Slow Cranking", "Diagnoses battery resistance, dead battery, or fuel delivery issues."),
#         'hot_term': ("Hot Battery Terminals", "Confirms high resistance in battery cables."),
#         'dead_bat': ("Dead Battery", "Checks for parasitic drain or total charging system collapse."),
#         'draw': ("Current Draw High", "Confirms a parasitic electrical drain."),
#         'ghost': ("Ghost Lights", "Points to a glitching Body Control Module (BCM)."),
#         'lock_err': ("Lock Errors", "Confirms BCM glitches."),
#         'no_dash': ("No Power to Dash", "Used to diagnose an ignition switch short."),
#         'key_stuck': ("Key Stuck in Ignition", "Confirms ignition switch failures.")
#     },
#     "Exhaust, Fuel & Cooling": {
#         'smoke_white': ("White Exhaust Smoke", "Primary indicator of a blown head gasket."),
#         'smoke_black': ("Black Exhaust Smoke", "Indicates a failed fuel pressure regulator (running rich)."),
#         'sulfur': ("Sulfur Egg Smell", "Diagnoses a clogged catalytic converter."),
#         'loss_pwr': ("Major Loss of Power", "Used alongside sulfur smell to confirm catalytic failure."),
#         'rich': ("Running Rich", "Checks for a lazy O2 sensor."),
#         'mpg': ("Poor Fuel MPG", "Confirms O2 sensor failure."),
#         'rough_idle': ("Rough Idle", "Diagnoses an EGR valve stuck open."),
#         'stall_stop': ("Stall at Stop", "Confirms EGR valve issues."),
#         'gas_smell': ("Gas Smell", "Points to an EVAP system leak."),
#         'cap_light': ("Gas Cap Light", "Confirms an EVAP leak."),
#         'ticking': ("Ticking Sound", "Used to diagnose an exhaust manifold leak."),
#         'cabin_smell': ("Exhaust in Cabin", "Confirms an exhaust manifold leak."),
#         'quiet_choke': ("Engine Choking", "Points to a collapsed muffler."),
#         'back_p': ("High Backpressure", "Confirms a muffler collapse."),
#         'coolant_loss': ("Coolant Loss (Internal)", "Used to diagnose head gasket breaches or internal block leaks.")
#     },
#     "Steering & Suspension": {
#         'bouncy': ("Bouncy Ride", "Diagnoses internal strut failure."),
#         'strut_leak': ("Oil on Strut", "Confirms strut failure."),
#         'clunk': ("Clunk on Bumps", "Used to check control arms, ball joints, or sway bar links."),
#         'wander': ("Steering Wanders", "Confirms dead control arm bushings."),
#         'abs_fault': ("Electronic ABS Fault", "Used to diagnose complete traction system paralysis."),
#         'traction_fault': ("Traction Control Fault", "Confirms system paralysis."),
#         'whine': ("Power Steering Whine", "Diagnoses power steering pump cavitation.")
#     }
# }
# 
# # ==========================================
# # 2. THE INFERENCE ENGINE CORE
# # ==========================================
# def evidence_cf(*conditions):
#     return min(conditions) if conditions else 0
# 
# def apply_rule(evidence, rule_cf=0.7):
#     return evidence * rule_cf
# 
# def combine_cf(cf_list):
#     if not cf_list: return 0
#     combined = cf_list[0]
#     for next_cf in cf_list[1:]:
#         combined = combined + next_cf * (1 - combined)
#     return combined
# 
# # ==========================================
# # 3. UI SETUP & STATE MANAGEMENT
# # ==========================================
# st.set_page_config(page_title="AutoSleuth KBS", layout="wide")
# st.title("🕵️‍♂️ AutoSleuth: Knowledge-Based Diagnostic System")
# st.markdown("This system uses Forward Chaining inference to diagnose vehicle faults based on 73 logical rules.")
# 
# # Dictionary to store user inputs
# p = {var: 0.0 for cat in QUESTIONS.values() for var in cat.keys()}
# 
# st.header("Step 1: Where are you experiencing issues?")
# st.write("Select the symptom categories to narrow down the questions. (This satisfies the 'Ask relevant questions' requirement).")
# 
# cols = st.columns(3)
# selected_categories = []
# for i, category in enumerate(QUESTIONS.keys()):
#     if cols[i % 3].checkbox(category, value=(i==0)): # Default open first one
#         selected_categories.append(category)
# 
# st.divider()
# 
# if selected_categories:
#     st.header("Step 2: Provide specific symptoms")
# 
#     # Dynamically generate questions based ONLY on selected categories
#     for cat in selected_categories:
#         with st.expander(f"⚙️ {cat} Symptoms", expanded=True):
#             cat_cols = st.columns(2)
#             for i, (var, (label, why_text)) in enumerate(QUESTIONS[cat].items()):
#                 col = cat_cols[i % 2]
#                 p[var] = col.slider(label, 0.0, 1.0, 0.0, key=var)
#                 # Explanation Facility: WHY a question is asked
#                 with col.expander("❓ Why ask this?"):
#                     st.caption(why_text)
# 
# # ==========================================
# # 4. RULE EVALUATION & TRACING
# # ==========================================
# if st.button("RUN FORWARD CHAINING INFERENCE 🔍", type="primary", use_container_width=True):
#     results = {}
#     rule_text = {}
#     trace = [] # Stores the step-by-step reasoning
#     R = 0.7
# 
#     trace.append("▶️ **INITIALIZING FORWARD CHAINING ENGINE...**")
#     trace.append("▶️ Extracting known facts from user input...")
# 
#     # Helper function to evaluate rules and log the reasoning step-by-step
#     def eval_rule(rule_num, fault, cf, logic):
#         trace.append(f"Evaluating Rule {rule_num}: Checking conditions for [{fault}] -> ({logic})")
#         if cf > 0:
#             if fault not in results: results[fault] = []
#             results[fault].append(cf)
#             rule_text[fault] = logic
#             trace.append(f"   🟢 **TRIGGERED**: Conditions met! Added evidence for {fault} (CF: {cf:.2f})")
#         else:
#             trace.append(f"   🔴 **SKIPPED**: Conditions not met.")
# 
#     # --- ENGINE RULES (1-15) ---
#     eval_rule(1, "Fuel Injector Suspect", apply_rule(evidence_cf(p['eng_light'], p['rpm_drop']), R), "IF Light + RPM Drop")
#     eval_rule(2, "Vacuum Leak Suspect", apply_rule(evidence_cf(p['eng_light'], p['trim']), R), "IF Light + Trim > 15%")
#     eval_rule(3, "Dirty MAF Sensor", apply_rule(evidence_cf(p['eng_light'], p['maf']), R), "IF Light + MAF Low")
#     eval_rule(4, "Throttle Body Obstruction", apply_rule(evidence_cf(p['stall'], p['idle']), R), "IF Stall + Idle < 500")
#     eval_rule(5, "Fuel Pump Dying", apply_rule(evidence_cf(p['stall'], p['fuel_p']), R), "IF Stall + Pressure Low")
#     eval_rule(6, "Ignition Breakdown", apply_rule(evidence_cf(p['misfire'], p['gap']), R), "IF Misfire + Wide Gap")
#     eval_rule(7, "Clogged Injector", apply_rule(evidence_cf(p['misfire'], p['pulse']), R), "IF Misfire + Weak Pulse")
#     eval_rule(8, "Coolant Escape", apply_rule(evidence_cf(p['temp'], p['coolant']), R), "IF Temp > 110C + Coolant Low")
#     eval_rule(9, "Cooling Fan Dead", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF Temp High + Fan RPM 0")
#     eval_rule(10, "Thermostat Frozen", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF Temp High + Thermo Closed")
#     eval_rule(11, "Oil Bleeding Out", apply_rule(evidence_cf(p['oil_p'], (1-p['oil_lvl'])), R), "IF Oil P Low + Oil Level Low")
#     eval_rule(12, "Oil Pump Cardiac Arrest", apply_rule(evidence_cf(p['oil_p'], p['oil_lvl']), R), "IF Oil P Low + Oil Level Normal")
#     eval_rule(13, "Lubrication Starvation", apply_rule(evidence_cf(p['knock'], (1-p['oil_lvl'])), R), "IF Knock + Wrong Viscosity")
#     eval_rule(14, "Timing Chain Jumped", apply_rule(evidence_cf(p['knock'], p['rpm_drop']), R), "IF Knock + Timing Off")
#     eval_rule(15, "Fuel Delivery DOA", apply_rule(evidence_cf(p['slow_crank'], p['fuel_p']), R), "IF Crank + No Start + No Pressure")
# 
#     # --- TRANSMISSION RULES (16-23) ---
#     eval_rule(16, "Slipping Clutches", apply_rule(evidence_cf(p['slip'], p['trans_low']), R), "IF Slip + Fluid Low")
#     eval_rule(17, "Burnt Friction Plates", apply_rule(evidence_cf(p['slip'], p['burnt']), R), "IF Slip + Fluid Burnt")
#     eval_rule(18, "Hydraulic Pressure Loss", apply_rule(evidence_cf(p['harsh'], p['trans_low']), R), "IF Harsh + Fluid Low")
#     eval_rule(19, "Solenoid Sabotage", apply_rule(evidence_cf(p['harsh'], p['solenoid']), R), "IF Harsh + No Response")
#     eval_rule(20, "Overheated Trans Fluid", apply_rule(evidence_cf(p['trans_temp'], p['load']), R), "IF Trans Temp + Load")
#     eval_rule(21, "Torque Converter Failure", apply_rule(evidence_cf(p['no_drive'], p['trans_low']), R), "IF No Drive + Fluid Low")
#     eval_rule(22, "Driveline Imbalance", apply_rule(evidence_cf(p['vibr_accel'], p['trans_low']), R), "IF Vibr + Mount Broken")
#     eval_rule(23, "CV Joint Murder", apply_rule(evidence_cf(p['click'], p['boot']), R), "IF Click + Boot Torn")
# 
#     # --- BRAKE RULES (24-32) ---
#     eval_rule(24, "Brake Fluid Leak", apply_rule(evidence_cf(p['brk_light'], p['brk_low']), R), "IF Light + Fluid Low")
#     eval_rule(25, "Master Cylinder Failure", apply_rule(evidence_cf(p['brk_light'], p['sink']), R), "IF Light + Pedal Sink")
#     eval_rule(26, "Pad Wear Out", apply_rule(evidence_cf(p['squeal'], p['pads']), R), "IF Squeal + Pads Low")
#     eval_rule(27, "Glazed Rotors", apply_rule(evidence_cf(p['squeal'], p['hard_p']), R), "IF Squeal + Hard Pedal")
#     eval_rule(28, "Air in Brake Lines", apply_rule(evidence_cf(p['spongy'], p['bubbles']), R), "IF Spongy + Bubbles")
#     eval_rule(29, "Warped Rotors", apply_rule(evidence_cf(p['pulsation'], p['shake']), R), "IF Pulsation + Shake")
#     eval_rule(30, "Seized Caliper", apply_rule(evidence_cf(p['pull'], p['burning']), R), "IF Pull + Burning")
#     eval_rule(31, "ABS Sensor Failure", apply_rule(evidence_cf(p['abs_light'], p['wheel_err']), R), "IF ABS Light + Wheel Err")
#     eval_rule(32, "Hydraulic Pump Failure", apply_rule(evidence_cf(p['abs_light'], p['abs_pump']), R), "IF ABS Light + Hard Pedal")
# 
#     # --- ELECTRICAL RULES (33-39) ---
#     eval_rule(33, "Alternator Undercharging", apply_rule(evidence_cf(p['bat_light'], p['volt']), R), "IF Bat Light + Volt < 13")
#     eval_rule(34, "Diode Bridge Failure", apply_rule(evidence_cf(p['bat_light'], p['ac_leak']), R), "IF Bat Light + AC Leak")
#     eval_rule(35, "Starter Solenoid Dead", apply_rule(evidence_cf(p['no_crank'], p['click_start']), R), "IF No Crank + Clicking")
#     eval_rule(36, "Battery Cable Resistance", apply_rule(evidence_cf(p['slow_crank'], p['hot_term']), R), "IF Slow Crank + Hot Term")
#     eval_rule(37, "Parasitic Drain", apply_rule(evidence_cf(p['dead_bat'], p['draw']), R), "IF Dead Bat + High Draw")
#     eval_rule(38, "Body Control Module Glitch", apply_rule(evidence_cf(p['ghost'], p['lock_err']), R), "IF Ghost Light + Lock Err")
#     eval_rule(39, "Ignition Switch Short", apply_rule(evidence_cf(p['no_dash'], p['key_stuck']), R), "IF No Dash + Key Stuck")
# 
#     # --- EXHAUST & EMISSION RULES (40-46) ---
#     eval_rule(40, "Catalytic Converter Clogged", apply_rule(evidence_cf(p['sulfur'], p['loss_pwr']), R), "IF Sulfur + No Power")
#     eval_rule(41, "O2 Sensor Lazy", apply_rule(evidence_cf(p['rich'], p['mpg']), R), "IF Rich + Poor MPG")
#     eval_rule(42, "EGR Valve Stuck Open", apply_rule(evidence_cf(p['rough_idle'], p['stall_stop']), R), "IF Rough Idle + Stall")
#     eval_rule(43, "EVAP System Leak", apply_rule(evidence_cf(p['gas_smell'], p['cap_light']), R), "IF Gas Smell + Cap Light")
#     eval_rule(44, "Exhaust Manifold Leak", apply_rule(evidence_cf(p['ticking'], p['cabin_smell']), R), "IF Ticking + Cabin Smell")
#     eval_rule(45, "Muffler Collapse", apply_rule(evidence_cf(p['quiet_choke'], p['back_p']), R), "IF Quiet Choke + Back P")
#     eval_rule(46, "Head Gasket Breach", apply_rule(evidence_cf(p['smoke_white'], p['coolant_loss']), R), "IF White Smoke + Coolant Loss")
# 
#     # --- STEERING & SUSPENSION (47-54) ---
#     eval_rule(47, "Strut Internal Failure", apply_rule(evidence_cf(p['bouncy'], p['strut_leak']), R), "IF Bouncy + Leak")
#     eval_rule(48, "Control Arm Bushing Dead", apply_rule(evidence_cf(p['clunk'], p['wander']), R), "IF Clunk + Wander")
#     eval_rule(49, "Ball Joint Wear", apply_rule(evidence_cf(p['clunk'], (1-p['clunk'])), R), "IF Creak + Camber Off")
#     eval_rule(50, "Power Steering Pump Cavitation", apply_rule(evidence_cf(p['whine'], (1-p['whine'])), R), "IF Whine + Fluid Low")
#     eval_rule(51, "Rack and Pinion Leak", apply_rule(evidence_cf(p['hard_p'], (1-p['hard_p'])), R), "IF Hard Steer + Loss")
#     eval_rule(52, "Tie Rod End Play", apply_rule(evidence_cf(p['shake'], (1-p['shake'])), R), "IF Shake Whl + Wear")
#     eval_rule(53, "Wheel Bearing Growl", apply_rule(evidence_cf(p['shake'], (1-p['shake'])), R), "IF Hum + Vibration")
#     eval_rule(54, "Sway Bar Link Snapped", apply_rule(evidence_cf(p['clunk'], (1-p['clunk'])), R), "IF Roll + Knock")
# 
#     # --- FUEL SYSTEM (55-60) ---
#     eval_rule(55, "Fuel Filter Clogged", apply_rule(evidence_cf(p['stall'], (1-p['stall'])), R), "IF Hesitation + Lean")
#     eval_rule(56, "Fuel Pressure Regulator Failed", apply_rule(evidence_cf(p['smoke_black'], (1-p['smoke_black'])), R), "IF Black Smoke + Gas in Vac")
#     eval_rule(57, "Fuel Tank Vent Blocked", apply_rule(evidence_cf(p['stall'], (1-p['stall'])), R), "IF Tank Hiss + Stall")
#     eval_rule(58, "Flex Fuel Sensor Error", apply_rule(evidence_cf(p['slow_crank'], (1-p['slow_crank'])), R), "IF Hard Start + Alc Err")
#     eval_rule(59, "Lift Pump Failure", apply_rule(evidence_cf(p['slow_crank'], (1-p['slow_crank'])), R), "IF Long Crank + Low Prime")
#     eval_rule(60, "Fuel Line Restriction", apply_rule(evidence_cf(p['stall'], (1-p['stall'])), R), "IF Lean Code + Kink")
# 
#     # --- COOLING SYSTEM (61-65) ---
#     eval_rule(61, "Radiator Strangled", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF Temp + Flow Blocked")
#     eval_rule(62, "Water Pump Stopped", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF Temp + No Flow")
#     eval_rule(63, "Internal Coolant Escape", apply_rule(evidence_cf(p['coolant_loss'], (1-p['coolant_loss'])), R), "IF Disappears + No Leak")
#     eval_rule(64, "Heat Circulation Broken", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF No Heat + Coolant Low")
#     eval_rule(65, "Heater Core Blocked", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF No Heat + Core Blocked")
# 
#     # --- COMBINED CONSPIRACIES (66-73) ---
#     eval_rule(66, "Alternator Sabotage", apply_rule(evidence_cf(p['eng_light'], p['bat_light'], p['rpm_drop']), R), "IF Eng Light + Bat Light + RPM Unstable")
#     eval_rule(67, "Shared Sensor Failure", apply_rule(evidence_cf(p['brk_light'], p['abs_light'], p['wheel_err']), R), "IF Brake Light + ABS Light + Wheel Err")
#     eval_rule(68, "Head Gasket Breach", apply_rule(evidence_cf(p['temp'], p['smoke_white'], p['coolant_loss']), R), "IF Temp High + White Smoke + Coolant Loss")
#     eval_rule(69, "System Paralysis", apply_rule(evidence_cf(p['abs_fault'], p['traction_fault'], p['wheel_err']), R), "IF ABS + Traction + Wheel Err")
#     eval_rule(70, "Charging System Collapse", apply_rule(evidence_cf(p['dead_bat'], p['slow_crank'], p['volt']), R), "IF Dead Bat + Slow Crank + Volt Low")
#     eval_rule(71, "Fuel/Ignition Conspiracy", apply_rule(evidence_cf(p['misfire'], (1-p['misfire']), p['trim']), R), "IF Misfire + O2 Flat + Trim High")
#     eval_rule(72, "Engine/Trans Co-Suspects", apply_rule(evidence_cf(p['eng_light'], p['trans_temp'], p['rpm_drop']), R), "IF Eng Light + Trans Temp + RPM Drop")
#     eval_rule(73, "Engine Internal Destruction", apply_rule(evidence_cf(p['oil_p'], p['knock'], p['temp']), R), "IF Oil Low + Knock + Temp High")
# 
#     trace.append("▶️ **INFERENCE COMPLETE.** Calculating final Certainty Factors...")
# 
#     # ==========================================
#     # 5. RANKING, DISPLAY & EXPLANATION FACILITY
#     # ==========================================
#     st.divider()
#     st.header("📋 Diagnostic Results")
# 
#     # Explanation Facility: HOW the conclusion was reached
#     with st.expander("🧠 View System Reasoning Trace (How I thought)", expanded=False):
#         for line in trace:
#             st.text(line)
# 
#     final_report = []
#     for fault, cf_list in results.items():
#         score = combine_cf(cf_list)
#         final_report.append({"fault": fault, "score": score, "logic": rule_text[fault], "multi": len(cf_list)})
# 
#     ranked = sorted(final_report, key=lambda x: x['score'], reverse=True)
# 
#     if not ranked:
#         st.success("Analysis Complete: No strong evidence found for a specific failure based on current input.")
#     else:
#         top_score = ranked[0]['score']
# 
#         for item in ranked:
#             score_pct = item['score'] * 100
#             if item['score'] == top_score:
#                 st.error(f"### 🚨 PRIMARY DIAGNOSIS ({score_pct:.1f}%) ➔ {item['fault']}")
#                 st.code(f"Primary Logic Triggered: {item['logic']}", language="text")
#                 if item['multi'] > 1:
#                     st.caption(f"ℹ️ Certainty boosted because {item['multi']} separate logical rules were triggered and combined.")
#             elif item['score'] >= 0.4:
#                 st.warning(f"**Secondary Suspect ({score_pct:.1f}%)** ➔ {item['fault']}")
#             else:
#                 pass # Hide low confidence ones to keep UI clean

import os
import subprocess
import requests

# Download cloudflared.exe
url = "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe"

response = requests.get(url)

with open("cloudflared.exe", "wb") as f:
    f.write(response.content)

print("Cloudflared downloaded successfully!")

# Start Streamlit app
streamlit_process = subprocess.Popen(
    ["streamlit", "run", "app.py"],
    shell=True
)

print("Streamlit started!")

# Start Cloudflare tunnel
cloudflare_process = subprocess.Popen(
    ["cloudflared.exe", "tunnel", "--url", "http://localhost:8501"],
    shell=True
)

#New Version

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # ==========================================
# # 1. THE INFERENCE ENGINE
# # ==========================================
# def evidence_cf(*conditions):
#     return min(conditions) if conditions else 0
# 
# def apply_rule(evidence, rule_cf=0.7):
#     return evidence * rule_cf
# 
# def combine_cf(cf_list):
#     if not cf_list: return 0
#     combined = cf_list[0]
#     for next_cf in cf_list[1:]:
#         combined = combined + next_cf * (1 - combined)
#     return combined
# 
# # ==========================================
# # 2. UI SETUP & PARAMETERS
# # ==========================================
# st.set_page_config(page_title="AutoSleuth 73 Rules", layout="wide")
# st.title("🕵️‍♂️ AutoSleuth: 73-Rule Master Terminal")
# 
# p = {}
# 
# with st.expander("🛠️ STEP 1: ENGINE & MECHANICAL CLUES", expanded=True):
#     c1, c2, c3 = st.columns(3)
#     p['eng_light'] = c1.slider("Engine Light ON", 0.0, 1.0, 0.0)
#     p['rpm_drop'] = c1.slider("RPM Drop", 0.0, 1.0, 0.0)
#     p['trim'] = c1.slider("Fuel Trim > 15%", 0.0, 1.0, 0.0)
#     p['maf'] = c1.slider("MAF Reading Low", 0.0, 1.0, 0.0)
#     p['stall'] = c1.slider("Engine Stalling", 0.0, 1.0, 0.0)
#     p['idle'] = c2.slider("Idle < 500 RPM", 0.0, 1.0, 0.0)
#     p['fuel_p'] = c2.slider("Fuel Pressure Low", 0.0, 1.0, 0.0)
#     p['misfire'] = c2.slider("Misfire Detected", 0.0, 1.0, 0.0)
#     p['gap'] = c2.slider("Spark Plug Gap Wide", 0.0, 1.0, 0.0)
#     p['pulse'] = c2.slider("Injector Pulse Weak", 0.0, 1.0, 0.0)
#     p['temp'] = c3.slider("Temp > 110C", 0.0, 1.0, 0.0)
#     p['coolant'] = c3.slider("Coolant Level Low", 0.0, 1.0, 0.0)
#     p['oil_p'] = c3.slider("Oil Pressure Low", 0.0, 1.0, 0.0)
#     p['oil_lvl'] = c3.slider("Oil Level Normal", 0.0, 1.0, 0.0)
#     p['knock'] = c3.slider("Knocking Sound", 0.0, 1.0, 0.0)
# 
# with st.expander("🛠️ STEP 2: TRANSMISSION & BRAKE CLUES"):
#     c1, c2 = st.columns(2)
#     p['slip'] = c1.slider("Gear Slip", 0.0, 1.0, 0.0)
#     p['trans_low'] = c1.slider("Trans Fluid Low", 0.0, 1.0, 0.0)
#     p['burnt'] = c1.slider("Fluid Burnt Smell", 0.0, 1.0, 0.0)
#     p['harsh'] = c1.slider("Harsh Shift", 0.0, 1.0, 0.0)
#     p['solenoid'] = c1.slider("No Solenoid Response", 0.0, 1.0, 0.0)
#     p['trans_temp'] = c1.slider("Trans Temp High", 0.0, 1.0, 0.0)
#     p['load'] = c1.slider("Heavy Load/Towing", 0.0, 1.0, 0.0)
#     p['no_drive'] = c1.slider("No Drive Engagement", 0.0, 1.0, 0.0)
#     p['vibr_accel'] = c2.slider("Vibration on Accel", 0.0, 1.0, 0.0)
#     p['click'] = c2.slider("Clicking on Turn", 0.0, 1.0, 0.0)
#     p['boot'] = c2.slider("CV Boot Torn", 0.0, 1.0, 0.0)
#     p['brk_light'] = c2.slider("Brake Light ON", 0.0, 1.0, 0.0)
#     p['brk_low'] = c2.slider("Brake Fluid Low", 0.0, 1.0, 0.0)
#     p['sink'] = c2.slider("Pedal Sinking", 0.0, 1.0, 0.0)
#     p['squeal'] = c2.slider("Brake Squeal", 0.0, 1.0, 0.0)
#     p['pads'] = c2.slider("Pads Low", 0.0, 1.0, 0.0)
#     p['hard_p'] = c2.slider("Hard Brake Pedal", 0.0, 1.0, 0.0)
# 
# with st.expander("🛠️ STEP 3: ELECTRICAL & EXHAUST CLUES"):
#     c1, c2 = st.columns(2)
#     p['spongy'] = c1.slider("Spongy Pedal", 0.0, 1.0, 0.0)
#     p['bubbles'] = c1.slider("Air Bubbles in Fluid", 0.0, 1.0, 0.0)
#     p['pulsation'] = c1.slider("Pedal Pulsation", 0.0, 1.0, 0.0)
#     p['shake'] = c1.slider("Shake at High Speed", 0.0, 1.0, 0.0)
#     p['pull'] = c1.slider("Vehicle Pulls Aside", 0.0, 1.0, 0.0)
#     p['burning'] = c1.slider("Burning Smell", 0.0, 1.0, 0.0)
#     p['abs_light'] = c1.slider("ABS Light ON", 0.0, 1.0, 0.0)
#     p['wheel_err'] = c1.slider("Wheel Speed Err", 0.0, 1.0, 0.0)
#     p['abs_pump'] = c1.slider("ABS Pump Noisy", 0.0, 1.0, 0.0)
#     p['bat_light'] = c2.slider("Battery Light ON", 0.0, 1.0, 0.0)
#     p['volt'] = c2.slider("Voltage < 13V", 0.0, 1.0, 0.0)
#     p['ac_leak'] = c2.slider("AC Leakage detected", 0.0, 1.0, 0.0)
#     p['no_crank'] = c2.slider("No Cranking", 0.0, 1.0, 0.0)
#     p['click_start'] = c2.slider("Clicking when starting", 0.0, 1.0, 0.0)
#     p['slow_crank'] = c2.slider("Slow Cranking", 0.0, 1.0, 0.0)
#     p['hot_term'] = c2.slider("Hot Battery Terminals", 0.0, 1.0, 0.0)
#     p['dead_bat'] = c2.slider("Dead Battery", 0.0, 1.0, 0.0)
#     p['smoke_white'] = c2.slider("White Exhaust Smoke", 0.0, 1.0, 0.0)
#     p['smoke_black'] = c2.slider("Black Exhaust Smoke", 0.0, 1.0, 0.0)
# 
# with st.expander("🛠️ STEP 4: STEERING & FINAL CLUES"):
#     c1, c2 = st.columns(2)
#     p['draw'] = c1.slider("Current Draw High", 0.0, 1.0, 0.0)
#     p['ghost'] = c1.slider("Ghost Lights", 0.0, 1.0, 0.0)
#     p['lock_err'] = c1.slider("Lock Errors", 0.0, 1.0, 0.0)
#     p['no_dash'] = c1.slider("No Power to Dash", 0.0, 1.0, 0.0)
#     p['key_stuck'] = c1.slider("Key Stuck in Ignition", 0.0, 1.0, 0.0)
#     p['sulfur'] = c1.slider("Sulfur Egg Smell", 0.0, 1.0, 0.0)
#     p['loss_pwr'] = c1.slider("Major Loss of Power", 0.0, 1.0, 0.0)
#     p['rich'] = c1.slider("Running Rich", 0.0, 1.0, 0.0)
#     p['mpg'] = c1.slider("Poor Fuel MPG", 0.0, 1.0, 0.0)
#     p['rough_idle'] = c1.slider("Rough Idle", 0.0, 1.0, 0.0)
#     p['stall_stop'] = c1.slider("Stall at Stop", 0.0, 1.0, 0.0)
#     p['gas_smell'] = c2.slider("Gas Smell", 0.0, 1.0, 0.0)
#     p['cap_light'] = c2.slider("Gas Cap Light", 0.0, 1.0, 0.0)
#     p['ticking'] = c2.slider("Ticking Sound", 0.0, 1.0, 0.0)
#     p['cabin_smell'] = c2.slider("Exhaust in Cabin", 0.0, 1.0, 0.0)
#     p['quiet_choke'] = c2.slider("Engine Choking", 0.0, 1.0, 0.0)
#     p['back_p'] = c2.slider("High Backpressure", 0.0, 1.0, 0.0)
#     p['coolant_loss'] = c2.slider("Coolant Loss (Internal)", 0.0, 1.0, 0.0)
#     p['bouncy'] = c2.slider("Bouncy Ride", 0.0, 1.0, 0.0)
#     p['strut_leak'] = c2.slider("Oil on Strut", 0.0, 1.0, 0.0)
#     p['clunk'] = c2.slider("Clunk on Bumps", 0.0, 1.0, 0.0)
#     p['wander'] = c2.slider("Steering Wanders", 0.0, 1.0, 0.0)
#     p['abs_fault'] = c2.slider("Electronic ABS Fault", 0.0, 1.0, 0.0)
#     p['traction_fault'] = c2.slider("Traction Control Fault", 0.0, 1.0, 0.0)
#     p['whine'] = c2.slider("Power Steering Whine", 0.0, 1.0, 0.0)
# 
# # ==========================================
# # 3. THE 73 LOGIC RULES (EXPLICIT)
# # ==========================================
# if st.button("RUN GLOBAL DIAGNOSTIC (73 RULES) 🔍", type="primary", use_container_width=True):
#     results = {}
#     R = 0.7
#     rule_text = {}
# 
#     def add_f(fault, cf, logic):
#         if cf > 0:
#             if fault not in results: results[fault] = []
#             results[fault].append(cf)
#             rule_text[fault] = logic
# 
#     # --- ENGINE RULES (1-15) ---
#     add_f("Fuel Injector Suspect", apply_rule(evidence_cf(p['eng_light'], p['rpm_drop']), R), "IF Light + RPM Drop")
#     add_f("Vacuum Leak Suspect", apply_rule(evidence_cf(p['eng_light'], p['trim']), R), "IF Light + Trim > 15%")
#     add_f("Dirty MAF Sensor", apply_rule(evidence_cf(p['eng_light'], p['maf']), R), "IF Light + MAF Low")
#     add_f("Throttle Body Obstruction", apply_rule(evidence_cf(p['stall'], p['idle']), R), "IF Stall + Idle < 500")
#     add_f("Fuel Pump Dying", apply_rule(evidence_cf(p['stall'], p['fuel_p']), R), "IF Stall + Pressure Low")
#     add_f("Ignition Breakdown", apply_rule(evidence_cf(p['misfire'], p['gap']), R), "IF Misfire + Wide Gap")
#     add_f("Clogged Injector", apply_rule(evidence_cf(p['misfire'], p['pulse']), R), "IF Misfire + Weak Pulse")
#     add_f("Coolant Escape", apply_rule(evidence_cf(p['temp'], p['coolant']), R), "IF Temp > 110C + Coolant Low")
#     add_f("Cooling Fan Dead", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF Temp High + Fan RPM 0")
#     add_f("Thermostat Frozen", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF Temp High + Thermo Closed")
#     add_f("Oil Bleeding Out", apply_rule(evidence_cf(p['oil_p'], (1-p['oil_lvl'])), R), "IF Oil P Low + Oil Level Low")
#     add_f("Oil Pump Cardiac Arrest", apply_rule(evidence_cf(p['oil_p'], p['oil_lvl']), R), "IF Oil P Low + Oil Level Normal")
#     add_f("Lubrication Starvation", apply_rule(evidence_cf(p['knock'], (1-p['oil_lvl'])), R), "IF Knock + Wrong Viscosity")
#     add_f("Timing Chain Jumped", apply_rule(evidence_cf(p['knock'], p['rpm_drop']), R), "IF Knock + Timing Off")
#     add_f("Fuel Delivery DOA", apply_rule(evidence_cf(p['slow_crank'], p['fuel_p']), R), "IF Crank + No Start + No Pressure")
# 
#     # --- TRANSMISSION RULES (16-23) ---
#     add_f("Slipping Clutches", apply_rule(evidence_cf(p['slip'], p['trans_low']), R), "IF Slip + Fluid Low")
#     add_f("Burnt Friction Plates", apply_rule(evidence_cf(p['slip'], p['burnt']), R), "IF Slip + Fluid Burnt")
#     add_f("Hydraulic Pressure Loss", apply_rule(evidence_cf(p['harsh'], p['trans_low']), R), "IF Harsh + Fluid Low")
#     add_f("Solenoid Sabotage", apply_rule(evidence_cf(p['harsh'], p['solenoid']), R), "IF Harsh + No Response")
#     add_f("Overheated Trans Fluid", apply_rule(evidence_cf(p['trans_temp'], p['load']), R), "IF Trans Temp + Load")
#     add_f("Torque Converter Failure", apply_rule(evidence_cf(p['no_drive'], p['trans_low']), R), "IF No Drive + Fluid Low")
#     add_f("Driveline Imbalance", apply_rule(evidence_cf(p['vibr_accel'], p['trans_low']), R), "IF Vibr + Mount Broken")
#     add_f("CV Joint Murder", apply_rule(evidence_cf(p['click'], p['boot']), R), "IF Click + Boot Torn")
# 
#     # --- BRAKE RULES (24-32) ---
#     add_f("Brake Fluid Leak", apply_rule(evidence_cf(p['brk_light'], p['brk_low']), R), "IF Light + Fluid Low")
#     add_f("Master Cylinder Failure", apply_rule(evidence_cf(p['brk_light'], p['sink']), R), "IF Light + Pedal Sink")
#     add_f("Pad Wear Out", apply_rule(evidence_cf(p['squeal'], p['pads']), R), "IF Squeal + Pads Low")
#     add_f("Glazed Rotors", apply_rule(evidence_cf(p['squeal'], p['hard_p']), R), "IF Squeal + Hard Pedal")
#     add_f("Air in Brake Lines", apply_rule(evidence_cf(p['spongy'], p['bubbles']), R), "IF Spongy + Bubbles")
#     add_f("Warped Rotors", apply_rule(evidence_cf(p['pulsation'], p['shake']), R), "IF Pulsation + Shake")
#     add_f("Seized Caliper", apply_rule(evidence_cf(p['pull'], p['burning']), R), "IF Pull + Burning")
#     add_f("ABS Sensor Failure", apply_rule(evidence_cf(p['abs_light'], p['wheel_err']), R), "IF ABS Light + Wheel Err")
#     add_f("Hydraulic Pump Failure", apply_rule(evidence_cf(p['abs_light'], p['abs_pump']), R), "IF ABS Light + Hard Pedal")
# 
#     # --- ELECTRICAL RULES (33-39) ---
#     add_f("Alternator Undercharging", apply_rule(evidence_cf(p['bat_light'], p['volt']), R), "IF Bat Light + Volt < 13")
#     add_f("Diode Bridge Failure", apply_rule(evidence_cf(p['bat_light'], p['ac_leak']), R), "IF Bat Light + AC Leak")
#     add_f("Starter Solenoid Dead", apply_rule(evidence_cf(p['no_crank'], p['click_start']), R), "IF No Crank + Clicking")
#     add_f("Battery Cable Resistance", apply_rule(evidence_cf(p['slow_crank'], p['hot_term']), R), "IF Slow Crank + Hot Term")
#     add_f("Parasitic Drain", apply_rule(evidence_cf(p['dead_bat'], p['draw']), R), "IF Dead Bat + High Draw")
#     add_f("Body Control Module Glitch", apply_rule(evidence_cf(p['ghost'], p['lock_err']), R), "IF Ghost Light + Lock Err")
#     add_f("Ignition Switch Short", apply_rule(evidence_cf(p['no_dash'], p['key_stuck']), R), "IF No Dash + Key Stuck")
# 
#     # --- EXHAUST & EMISSION RULES (40-46) ---
#     add_f("Catalytic Converter Clogged", apply_rule(evidence_cf(p['sulfur'], p['loss_pwr']), R), "IF Sulfur + No Power")
#     add_f("O2 Sensor Lazy", apply_rule(evidence_cf(p['rich'], p['mpg']), R), "IF Rich + Poor MPG")
#     add_f("EGR Valve Stuck Open", apply_rule(evidence_cf(p['rough_idle'], p['stall_stop']), R), "IF Rough Idle + Stall")
#     add_f("EVAP System Leak", apply_rule(evidence_cf(p['gas_smell'], p['cap_light']), R), "IF Gas Smell + Cap Light")
#     add_f("Exhaust Manifold Leak", apply_rule(evidence_cf(p['ticking'], p['cabin_smell']), R), "IF Ticking + Cabin Smell")
#     add_f("Muffler Collapse", apply_rule(evidence_cf(p['quiet_choke'], p['back_p']), R), "IF Quiet Choke + Back P")
#     add_f("Head Gasket Breach", apply_rule(evidence_cf(p['smoke_white'], p['coolant_loss']), R), "IF White Smoke + Coolant Loss")
# 
#     # --- STEERING & SUSPENSION (47-54) ---
#     add_f("Strut Internal Failure", apply_rule(evidence_cf(p['bouncy'], p['strut_leak']), R), "IF Bouncy + Leak")
#     add_f("Control Arm Bushing Dead", apply_rule(evidence_cf(p['clunk'], p['wander']), R), "IF Clunk + Wander")
#     add_f("Ball Joint Wear", apply_rule(evidence_cf(p['clunk'], (1-p['clunk'])), R), "IF Creak + Camber Off")
#     add_f("Power Steering Pump Cavitation", apply_rule(evidence_cf(p['whine'], (1-p['whine'])), R), "IF Whine + Fluid Low")
#     add_f("Rack and Pinion Leak", apply_rule(evidence_cf(p['hard_p'], (1-p['hard_p'])), R), "IF Hard Steer + Loss")
#     add_f("Tie Rod End Play", apply_rule(evidence_cf(p['shake'], (1-p['shake'])), R), "IF Shake Whl + Wear")
#     add_f("Wheel Bearing Growl", apply_rule(evidence_cf(p['shake'], (1-p['shake'])), R), "IF Hum + Vibration")
#     add_f("Sway Bar Link Snapped", apply_rule(evidence_cf(p['clunk'], (1-p['clunk'])), R), "IF Roll + Knock")
# 
#     # --- FUEL SYSTEM (55-60) ---
#     add_f("Fuel Filter Clogged", apply_rule(evidence_cf(p['stall'], (1-p['stall'])), R), "IF Hesitation + Lean")
#     add_f("Fuel Pressure Regulator Failed", apply_rule(evidence_cf(p['smoke_black'], (1-p['smoke_black'])), R), "IF Black Smoke + Gas in Vac")
#     add_f("Fuel Tank Vent Blocked", apply_rule(evidence_cf(p['stall'], (1-p['stall'])), R), "IF Tank Hiss + Stall")
#     add_f("Flex Fuel Sensor Error", apply_rule(evidence_cf(p['slow_crank'], (1-p['slow_crank'])), R), "IF Hard Start + Alc Err")
#     add_f("Lift Pump Failure", apply_rule(evidence_cf(p['slow_crank'], (1-p['slow_crank'])), R), "IF Long Crank + Low Prime")
#     add_f("Fuel Line Restriction", apply_rule(evidence_cf(p['stall'], (1-p['stall'])), R), "IF Lean Code + Kink")
# 
#     # --- COOLING SYSTEM (61-65) ---
#     add_f("Radiator Strangled", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF Temp + Flow Blocked")
#     add_f("Water Pump Stopped", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF Temp + No Flow")
#     add_f("Internal Coolant Escape", apply_rule(evidence_cf(p['coolant_loss'], (1-p['coolant_loss'])), R), "IF Disappears + No Leak")
#     add_f("Heat Circulation Broken", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF No Heat + Coolant Low")
#     add_f("Heater Core Blocked", apply_rule(evidence_cf(p['temp'], (1-p['temp'])), R), "IF No Heat + Core Blocked")
# 
#     # --- COMBINED CONSPIRACIES (66-73) ---
#     add_f("Alternator Sabotage", apply_rule(evidence_cf(p['eng_light'], p['bat_light'], p['rpm_drop']), R), "IF Eng Light + Bat Light + RPM Unstable")
#     add_f("Shared Sensor Failure", apply_rule(evidence_cf(p['brk_light'], p['abs_light'], p['wheel_err']), R), "IF Brake Light + ABS Light + Wheel Err")
#     add_f("Head Gasket Breach", apply_rule(evidence_cf(p['temp'], p['smoke_white'], p['coolant_loss']), R), "IF Temp High + White Smoke + Coolant Loss")
#     add_f("System Paralysis", apply_rule(evidence_cf(p['abs_fault'], p['traction_fault'], p['wheel_err']), R), "IF ABS + Traction + Wheel Err")
#     add_f("Charging System Collapse", apply_rule(evidence_cf(p['dead_bat'], p['slow_crank'], p['volt']), R), "IF Dead Bat + Slow Crank + Volt Low")
#     add_f("Fuel/Ignition Conspiracy", apply_rule(evidence_cf(p['misfire'], (1-p['misfire']), p['trim']), R), "IF Misfire + O2 Flat + Trim High")
#     add_f("Engine/Trans Co-Suspects", apply_rule(evidence_cf(p['eng_light'], p['trans_temp'], p['rpm_drop']), R), "IF Eng Light + Trans Temp + RPM Drop")
#     add_f("Engine Internal Destruction", apply_rule(evidence_cf(p['oil_p'], p['knock'], p['temp']), R), "IF Oil Low + Knock + Temp High")
# 
#     # ==========================================
#     # 4. RANKING & DISPLAY
#     # ==========================================
#     final_report = []
#     for fault, cf_list in results.items():
#         score = combine_cf(cf_list)
#         final_report.append({"fault": fault, "score": score, "logic": rule_text[fault], "multi": len(cf_list)})
# 
#     ranked = sorted(final_report, key=lambda x: x['score'], reverse=True)
# 
#     if not ranked:
#         st.success("Analysis Complete: No evidence found.")
#     else:
#         st.header("📋 Final Diagnostic Ranking")
#         top_score = ranked[0]['score']
# 
#         for item in ranked:
#             score_pct = item['score'] * 100
#             if item['score'] == top_score:
#                 st.error(f"### 🚨 PRIMARY SUSPECT ({score_pct:.1f}%) ➔ {item['fault']}")
#                 st.code(f"Logic Triggered: {item['logic']}", language="text")
#                 if item['multi'] > 1:
#                     st.caption(f"ℹ️ Score boosted by {item['multi']} separate logic rules (Combined CF applied).")
#             elif item['score'] >= 0.4:
#                 st.info(f"**High Confidence ({score_pct:.1f}%)** ➔ {item['fault']}")
#             else:
#                 st.success(f"**Low Confidence ({score_pct:.1f}%)** ➔ {item['fault']}")

import os
import subprocess

# Kill any running cloudflared processes
try:
    subprocess.run(["taskkill", "/f", "/im", "cloudflared.exe"], capture_output=True, shell=True)
    print("Killed existing cloudflared processes")
except:
    print("No cloudflared process found")

# Wait a moment
import time
time.sleep(2)

# Now try to delete the file
try:
    if os.path.exists("cloudflared.exe"):
        os.remove("cloudflared.exe")
        print("Old file removed successfully")
except PermissionError:
    print("Still can't delete - try closing your terminal and reopening")

import os
import time

try:
    if os.path.exists("cloudflared.exe"):
        # Rename it instead of deleting
        os.rename("cloudflared.exe", "cloudflared_old.exe")
        print("File renamed instead of deleted")
except PermissionError:
    print("File is in use. Please close any terminals running cloudflared")

# Skip all cloudflared code - just run this:
import subprocess
import sys

# Install streamlit if needed
subprocess.check_call([sys.executable, "-m", "pip", "install", "streamlit"])

# Run the app directly
subprocess.run(["streamlit", "run", "app.ipynb"])

import os

if os.path.exists("cloudflared.exe"):
    os.remove("cloudflared.exe")

print("Old file removed")

import subprocess
import requests

# Download cloudflared.exe
url = "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe"

r = requests.get(url)

with open("cloudflared.exe", "wb") as f:
    f.write(r.content)

print("Downloaded cloudflared")

# Start Streamlit
subprocess.Popen(
    ["streamlit", "run", "app.py"],
    shell=True
)

print("Streamlit started")

# Start Cloudflare tunnel
subprocess.Popen(
    ["cloudflared.exe", "tunnel", "--url", "http://localhost:8501"],
    shell=True
)



#old version

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # ==========================================
# # 1. CERTAINTY FACTOR FUNCTIONS
# # ==========================================
# def evidence_cf(*conditions):
#     return min(conditions)
# 
# def apply_rule(evidence, rule_cf=0.7):
#     return evidence * rule_cf
# 
# # ==========================================
# # 2. THE RULE DATABASE (EXPLAINABILITY)
# # ==========================================
# # This dictionary maps every suspect to the exact rule that caught them.
# rule_database = {
#     "Fuel Injector Suspect": "IF Engine Light = ON AND RPM Drop = true",
#     "Vacuum Leak Suspect": "IF Engine Light = ON AND Fuel Trim > 15%",
#     "Dirty MAF Sensor": "IF Engine Light = ON AND MAF Reading < threshold",
#     "Throttle Body Obstruction": "IF Engine Stall = true AND Idle RPM < 500",
#     "Fuel Pump Dying": "IF Engine Stall = true AND Fuel Pressure < 30psi",
#     "Ignition System Breakdown": "IF Misfire Detected = true AND Spark Plug Gap > 1.6mm",
#     "Clogged Injector": "IF Misfire Detected = true AND Injector Pulse Weak = true",
#     "Coolant Escape": "IF Engine Temp > 110C AND Coolant Level < min",
#     "Cooling Fan Dead": "IF Engine Temp > 110C AND Radiator Fan RPM = 0",
#     "Thermostat Frozen Shut": "IF Engine Temp > 110C AND Thermostat Open = false",
#     "Oil Bleeding Out": "IF Oil Pressure < 10psi AND Oil Level < min",
#     "Oil Pump Cardiac Arrest": "IF Oil Pressure < 10psi AND Oil Level = normal",
#     "Lubrication Starvation": "IF Knocking Sound = true AND Oil Viscosity Wrong = true",
#     "Timing Chain Jumped": "IF Knocking Sound = true AND Timing Advance Off = true",
#     "Fuel Delivery DOA": "IF Crank = true AND Start = false AND Fuel Pressure = 0"
# }
# 
# # ==========================================
# # 3. STREAMLIT UI SETUP & LAYOUT
# # ==========================================
# st.set_page_config(page_title="AutoSleuth Expert System", page_icon="🕵️‍♂️", layout="wide")
# 
# st.title("🕵️‍♂️ AutoSleuth: Engine Crimes Diagnostic Terminal")
# st.markdown("Adjust the sliders below based on your confidence in each symptom.")
# 
# st.header("Symptom Input")
# col1, col2, col3 = st.columns(3)
# 
# with col1:
#     st.subheader("General Symptoms")
#     engine_light = st.slider("Check Engine Light ON", 0.0, 1.0, 0.0)
#     rpm_drop = st.slider("RPM Drop", 0.0, 1.0, 0.0)
#     engine_stall = st.slider("Engine Stalling", 0.0, 1.0, 0.0)
#     misfire_detected = st.slider("Misfire Detected", 0.0, 1.0, 0.0)
#     knocking_sound = st.slider("Knocking Sound", 0.0, 1.0, 0.0)
#     crank_turns = st.slider("Engine Cranks", 0.0, 1.0, 0.0)
#     engine_starts = st.slider("Engine Starts successfully", 0.0, 1.0, 0.0)
# 
# with col2:
#     st.subheader("Air & Fuel Delivery")
#     fuel_trim_high = st.slider("Fuel Trim > 15%", 0.0, 1.0, 0.0)
#     maf_reading_low = st.slider("MAF Reading Low", 0.0, 1.0, 0.0)
#     idle_rpm_low = st.slider("Idle RPM < 500", 0.0, 1.0, 0.0)
#     fuel_pressure_low = st.slider("Fuel Pressure Low (< 30psi)", 0.0, 1.0, 0.0)
#     injector_pulse_weak = st.slider("Injector Pulse Weak", 0.0, 1.0, 0.0)
#     spark_plug_gap_wide = st.slider("Spark Plug Gap > 1.6mm", 0.0, 1.0, 0.0)
# 
# with col3:
#     st.subheader("Cooling & Lubrication")
#     engine_temp_high = st.slider("Engine Temp > 110C", 0.0, 1.0, 0.0)
#     coolant_level_low = st.slider("Coolant Level Low", 0.0, 1.0, 0.0)
#     radiator_fan_dead = st.slider("Radiator Fan RPM = 0", 0.0, 1.0, 0.0)
#     thermostat_closed = st.slider("Thermostat Closed (Stuck)", 0.0, 1.0, 0.0)
#     oil_pressure_low = st.slider("Oil Pressure Low (< 10psi)", 0.0, 1.0, 0.0)
#     oil_level_low = st.slider("Oil Level Low", 0.0, 1.0, 0.0)
#     oil_level_normal = st.slider("Oil Level Normal", 0.0, 1.0, 0.0)
#     oil_viscosity_wrong = st.slider("Oil Viscosity Wrong", 0.0, 1.0, 0.0)
#     timing_advance_off = st.slider("Timing Advance Off", 0.0, 1.0, 0.0)
# 
# st.divider()
# 
# # ==========================================
# # 4. DIAGNOSIS ENGINE
# # ==========================================
# RULE_CF = 0.7
# 
# if st.button("Run Diagnostics 🔍", use_container_width=True, type="primary"):
#     st.header("📋 Final Diagnostic Report")
# 
#     suspects = {
#         "Fuel Injector Suspect": apply_rule(evidence_cf(engine_light, rpm_drop), RULE_CF),
#         "Vacuum Leak Suspect": apply_rule(evidence_cf(engine_light, fuel_trim_high), RULE_CF),
#         "Dirty MAF Sensor": apply_rule(evidence_cf(engine_light, maf_reading_low), RULE_CF),
#         "Throttle Body Obstruction": apply_rule(evidence_cf(engine_stall, idle_rpm_low), RULE_CF),
#         "Fuel Pump Dying": apply_rule(evidence_cf(engine_stall, fuel_pressure_low), RULE_CF),
#         "Ignition System Breakdown": apply_rule(evidence_cf(misfire_detected, spark_plug_gap_wide), RULE_CF),
#         "Clogged Injector": apply_rule(evidence_cf(misfire_detected, injector_pulse_weak), RULE_CF),
#         "Coolant Escape": apply_rule(evidence_cf(engine_temp_high, coolant_level_low), RULE_CF),
#         "Cooling Fan Dead": apply_rule(evidence_cf(engine_temp_high, radiator_fan_dead), RULE_CF),
#         "Thermostat Frozen Shut": apply_rule(evidence_cf(engine_temp_high, thermostat_closed), RULE_CF),
#         "Oil Bleeding Out": apply_rule(evidence_cf(oil_pressure_low, oil_level_low), RULE_CF),
#         "Oil Pump Cardiac Arrest": apply_rule(evidence_cf(oil_pressure_low, oil_level_normal), RULE_CF),
#         "Lubrication Starvation": apply_rule(evidence_cf(knocking_sound, oil_viscosity_wrong), RULE_CF),
#         "Timing Chain Jumped": apply_rule(evidence_cf(knocking_sound, timing_advance_off), RULE_CF),
#         "Fuel Delivery DOA": apply_rule(evidence_cf(crank_turns, (1.0 - engine_starts), fuel_pressure_low), RULE_CF)
#     }
# 
#     # Sort from highest to lowest
#     ranked_suspects = sorted(suspects.items(), key=lambda item: item[1], reverse=True)
# 
#     # Find what the highest actual score is (so we can check for ties)
#     highest_score = ranked_suspects[0][1] if ranked_suspects else 0
# 
#     found_suspect = False
#     for fault, certainty in ranked_suspects:
#         if certainty > 0:
#             found_suspect = True
# 
#             # --- THE NEW RULE EXPLAINER LOGIC ---
#             if certainty == highest_score:
#                 st.error(f"🚨 **PRIMARY SUSPECT ({certainty*100:.1f}%)** ➔ {fault}")
#                 # Print the exact rule that triggered this diagnosis!
#                 st.code(f"Rule Triggered: {rule_database[fault]}", language="text")
#                 st.write("") # Adds a little space
# 
#             # The rest of the suspects print normally below the top one
#             elif certainty >= 0.5:
#                 st.warning(f"**High Confidence ({certainty*100:.1f}%)** ➔ {fault}")
#             elif certainty >= 0.3:
#                 st.info(f"**Medium Confidence ({certainty*100:.1f}%)** ➔ {fault}")
#             else:
#                 st.success(f"**Low Confidence ({certainty*100:.1f}%)** ➔ {fault}")
# 
#     if not found_suspect:
#         st.success("✅ No significant evidence found for Engine Crimes. The engine looks clear based on current inputs.")